In [73]:
import numpy as np
import pandas as pd

In [74]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [75]:
df = pd.read_csv('C:\\Users\\ACER\\Desktop\\Projects\\Machine Learning Based Real Estate System\\Dataset\\Cleaned_properties.csv')

df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1564,2 BHK Flat in Sector 37D Gurgaon,flat,signature global the millennia,0.55,9166.0,600.0,Super Built up area 600(55.74 sq.m.),2,2,3,not available,"Sector 37D Gurgaon, Gurgaon, Haryana",3.0,NaN,0 to 1 Year Old,"['Jharsha Chowk', 'Hero Honda Chowk', 'Rajiv C...",We are the proud owners of this 2 bhk apartmen...,[],NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3247,2 BHK Flat in Sector 108 Gurgaon,flat,raheja vedaanta,0.65,4761.0,1365.0,Super Built up area 1365(126.81 sq.m.),2,2,2,pooja room,"Dwarka Expressway, Sector 108 Gurgaon, Gurgaon...",5.0,East,1 to 5 Year Old,NaN,Available 2 bhk very spacious apartment in rah...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Li...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."
332,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,1.19,5505.0,2162.0,Super Built up area 1726(160.35 sq.m.),3,3,2,others,"Middle Floor Tower B, Sector 90 Gurgaon, Gurga...",11.0,South-East,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",Dlf regal garden sector 90 north-East facing 3...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4.5 out ..."
739,3 BHK Flat in Sector 49 Gurgaon,flat,vatika city,2.10,10418.0,2016.0,Super Built up area 2015.58(187.25 sq.m.)Built...,3,3,3,pooja room,"Vatika City, Sector 49 Gurgaon, Gurgaon, Haryana",9.0,South,5 to 10 Year Old,"['BOB ATM', 'PNB ATM', 'HDFC bank ATM', 'YES b...",A very good 3bhk plus store room flat for sale...,"['3 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Water purifier', 'Power Back-up', 'Feng Shui...","['Green Area5 out of 5', 'Construction4 out of..."
2392,4 BHK Flat in Sector 92 Gurgaon,flat,sare petioles,1.30,6373.0,2040.0,Built Up area: 2040 (189.52 sq.m.),4,4,0,not available,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",7.0,NaN,undefined,NaN,Best in class property available at sector 92 ...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [76]:
df.shape

(3961, 20)

In [77]:
df.duplicated().sum()

0

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [79]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [80]:
df.insert(loc=3, column='sector', value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon', '').str.strip())

In [81]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 77 Gurgaon,flat,umang winter hills,Sector 77,1.00,7500.0,1333.0,Carpet area: 1340 (124.49 sq.m.),2,2,2,not available,"Sector 77 Gurgaon, Gurgaon, Haryana",3.0,NaN,0 to 1 Year Old,"['Entertainland Mall', 'Delhi Jaipur Expresswa...",Internal park facing property and have best la...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector 65 Gurgaon,flat,emaar mgf emerald estate,Sector 65,1.75,12544.0,1395.0,Super Built up area 1395(129.6 sq.m.)Carpet ar...,3,3,3,servant room,"Sector 65 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Sector 53-54 Metro Station', 'Central Plaza ...",A well maintained flat in emerald estate,"['1 Exhaust Fan', '3 Geyser', '7 Light', '1 Ch...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area4 out of 5', 'Construction4 out of..."
2,9 Bedroom House for sale in Sector 54 Gurgaon,house,suncity township,Sector 54,2.00,30968.0,646.0,Plot area 60Built Up area: 60 sq.m.Carpet area...,9,9,3,servant room,NaN,11.0,North,1 to 5 Year Old,"['Sector 54 chowk metro station', 'Sector metr...",It is a property built in g block. It consists...,"['1 Water Purifier', '9 Fan', '1 Fridge', '1 E...",['Internet/wi-fi connectivity'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."
3,4 Bedroom House for sale in Sector 108 Gurgaon,house,independent,Sector 108,1.70,5666.0,3000.0,Built Up area: 3000 (278.71 sq.m.)Carpet area:...,4,4,3+,not available,"Sector 108, Sector 108 Gurgaon, Gurgaon, Haryana",1.0,North-East,undefined,NaN,Best in class property available at sector 108...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
4,3 BHK Flat in Sector 81 Gurgaon,flat,dlf the ultima,Sector 81,2.30,10994.0,2092.0,Super Built up area 2092(194.35 sq.m.),3,4,3+,servant room,"123, Sector 81 Gurgaon, Gurgaon, Haryana",6.0,East,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",Available for sale in dlf the ultima is one of...,"['8 Fan', '1 Fridge', '1 Exhaust Fan', '7 Geys...","['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction4 out of..."

In [82]:
df['sector'] = df['sector'].str.lower()

In [83]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
nirvana country                                               53
sector 37c                                                    53
sector 70                                                     53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
sector 113                                                    43
dlf phase 2                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 111                                                    22
sector 67a                                                    22
dlf phase 3                                                   22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sushant lok phase 3                                           16
sector 110                                                    16
sector 60                                                     15
sector 14                                                     15
sector 63                                                     15
sector 3                                                      14
dlf phase 5                                                   14
sector 52                                                     14
gwal pahari                                                   14
sector 1 imt manesar                                          14
sector 76                                                     14
sector 53                                                     14
rajendra park                                                 14
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 46                                                     13
uppals southend                                               12
sector 50                                                     12
sector 39                                                     12
sector 93                                                     12
sohna road                                                    12
sector 38                                                     12
sector 31                                                     12
sector 47                                                     11
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 55                                                      9
sector 95a                                                     9
sector 4                                                       9
ashok vihar phase 2                                            9
south city 1                                                   9
malibu town                                                    8
sector 57                                                      8
mehrauli  road                                                 8
dwarka expressway                                              8
sector 89 a                                                    8
sector 43                                                      8
sector 40                                                      8
sector 10a                                                     8
c block sushant lok phase 1                                    8
sector 59                                                      8
palam vihar extension                                          8
sector 11                                                      7
surat nagar 1                                                  7
new colony                                                     7
sector 58                                                      7
sector 36 sohna                                                7
mianwali colony                                                7
sector 51                                                      7
sector 26                                                      7
jyoti park                                                     6
jacobpura                                                      6
sector 1                                                       6
rajiv nagar                                                    6
sector 5                                                       6
ashok vihar                                                    6
subhash nagar                                                  5
dayanand colony                                                5
new palam vihar                                                5
sushant lok phase 2                                            5
saraswati vihar                                                5
sector 105                                                     5
sector 80                                                      5
sector 30                                                      5
sector 2                                                       5
sector 9                                                       5
chakkarpur                                                     5
arjun nagar                                                    5
manesar                                                        5
sector 23a                                                     5
greenwood city                                                 5
sector 28                                                      5
ansal plaza                                                    5
sector 17                                                      4
vishnu garden                                                  4
sector 12a                                                     4
devilal colony                                                 4
ravi nagar                                                     4
surya vihar                                                    4
valley view estate                                             4
baldev nagar                                                   4
sector 12                                                      4
bhim nagar                                                     4
sector 36                                                      4
sector 45                                                      4
suncity                                                        4
dharam colony                                                  4
adarsh nagar                                                   4
krishna colony                                                 4
shivaji nagar                                                  4
shivpuri                                                       4
garhi harsaru                                                  4
madanpuri                                                      4
new                                                            4
imt manesar                                                    4
sector 3a                                                      4
sector 6                                                       4
bhondsi                                                        4
shakti nagar                                                   3
gandhi nagar                                                   3
patel nagar                                                    3
sector 15                                                      3
sector 23                                                      3
a block sushant lok phase 1                                    3
sector 88b                                                     3
sector 17a                                                     3
sector 73                                                      3
sector 8                                                       3
prem nagar                                                     3
maruti kunj                                                    3
sector 17b                                                     3
mg road                                                        3
sector 110 a                                                   3
sector 27                                                      3
b block sushant lok phase 1                                    3
laxmi garden                                                   3
sector 24                                                      2
mohan nagar                                                    2
block a surya vihar                                            2
new palam vihar phase 2                                        2
faridabad road                                                 2
sheetla colony                                                 2
sushant lok                                                    2
hira nagar                                                     2
bissar                                                         2
surat nagar                                                    2
sector-2 sohna                                                 2
rajiv chowk                                                    2
shankar vihar                                                  2
sispal vihar                                                   2
nars                                                           2
manohar nagar                                                  2
acharya puri                                                   2
pratap nagar                                                   2
golf course ext road                                           2
sector 41                                                      2
daulatabad                                                     2
iffco chowk                                                    2
golf course road                                               2
shanti nagar                                                   2
lajpat nagar                                                   2
farukhnagar                                                    2
new basti                                                      2
surat nagar phase 2                                            2
sector 15 part 1                                               2
mayfield garden                                                2
sector-11 sohna                                                2
ambience island                                                2
, delhi ncr                                                    2
west rajiv nagar                                               2
sector 15 part 2                                               2
rosewood                                                       2
sohna  road                                                    2
sector 21                                                      2
bhawani enclave                                                2
samaspur                                                       2
sector 32                                                      2
new palam vihar phase 1                                        2
gopal nagar, garhi ghasita, sonipat                            1
huda saraswati vihar                                           1
alipur                                                         1
park view                                                      1
nirvana country pocket h                                       1
sector 13                                                      1
cyber city                                                     1
ravi nager basai road                                          1
rajiv colony                                                   1
sector-5 sohna                                                 1
kheri                                                          1
new colony, sector 7                                           1
saroop garden rajendra park                                    1
pataudi road                                                   1
ashok vihar phase i                                            1
carterpuri village                                             1
ashok vihar phase 3                                            1
shivji park colony                                             1
laxman vihar, railway road,                                    1
near pataudi chowk                                             1
dhankot                                                        1
devi lal colony gali no 12 gurgaon nr omkar public school      1
damdma                                                         1
hsiidc plot sector 1 imt manesar                               1
bhimgarh kheri phase 3                                         1
sultanpur                                                      1
sector-35 sohna                                                1
sector 37b                                                     1
new jyoti park                                                 1
tekchand nagar                                                 1
rattan garden                                                  1
laxmna vihar, phase 2                                          1
khandsa                                                        1
near sector 1 market                                           1
hno 13 sagar enclave sura                                      1
naharpur rupa                                                  1
lucknow                                                        1
sector 17c                                                     1
sector 42                                                      1
godrej aria , sector 79 ,                                      1
heritage city                                                  1
sector 4 urban estate                                          1
jacobpura near sadar bazar                                     1
sai kunj                                                       1
udyog vihar phase 1                                            1
south city                                                     1
sector 9b                                                      1
part 3 sector 5                                                1
mahavir pura                                                   1
anand garden, sector-105                                       1
saraswati enclave                                              1
sector-5 sheetla colony                                        1
g block dlf city phase 1                                       1
begampur khatola                                               1
near khandsa road                                              1
near euro                                                      1
sector 5 chowk                                                 1
mahalaxmi garden, rajendra place                               1
sec 3 bhim vihar part 1 bhimgher kheri                         1
v block dlf phase 3                                            1
old delhi road, opp sector-14                                  1
bhora kalan                                                    1
near nand hospital                                             1
om nagar                                                       1
kanahi                                                         1
bptp                                                           1
ram nagar                                                      1
b1 block sector 57                                             1
garauli kalan                                                  1
ansal's palam vihar                                            1
civil l                                                        1
jat colony,fazilpur/taj nagar road                             1
sector 37a                                                     1
block h ashok vihar phase iii extension                        1
vir nagar                                                      1
sector 21a faridabad                                           1
sadar bazar                                                    1
block g sector-57                                              1
ats marigold                                                   1
sector-7 hous                                                  1
urban estate, sector 5                                         1
Name: count, dtype: int64

In [84]:
# --- Normalize formatting issues / typos first ---
df['sector'] = df['sector'].str.strip()
df['sector'] = df['sector'].str.replace('sector-33 sohna', 'sector 33 sohna road')
df['sector'] = df['sector'].str.replace('sector-2 sohna', 'sector 2 sohna road')
df['sector'] = df['sector'].str.replace('sector-11 sohna', 'sector 11 sohna road')
df['sector'] = df['sector'].str.replace('sector-5 sohna', 'sector 5 sohna road')
df['sector'] = df['sector'].str.replace('sector-35 sohna', 'sector 35 sohna road')
df['sector'] = df['sector'].str.replace('sohna  road', 'sohna road')
df['sector'] = df['sector'].str.replace('mehrauli  road', 'mehrauli road')
df['sector'] = df['sector'].str.replace('sector 89 a', 'sector 89a')
df['sector'] = df['sector'].str.replace('sector 110 a', 'sector 110a')
df['sector'] = df['sector'].str.replace('sector 15 part 1', 'sector 15')
df['sector'] = df['sector'].str.replace('sector 15 part 2', 'sector 15')

# --- Known named-locality to sector mapping ---
df['sector'] = df['sector'].str.replace('sohna', 'sohna road')
df['sector'] = df['sector'].str.replace('rajendra park', 'sector 105')
df['sector'] = df['sector'].str.replace('nirvana country', 'sector 50')
df['sector'] = df['sector'].str.replace('dlf phase 1', 'sector 26')
df['sector'] = df['sector'].str.replace('dlf phase 2', 'sector 25')
df['sector'] = df['sector'].str.replace('dlf phase 3', 'sector 24')
df['sector'] = df['sector'].str.replace('dlf phase 4', 'sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 5', 'sector 43')
df['sector'] = df['sector'].str.replace('sushant lok phase 1', 'sector 43')
df['sector'] = df['sector'].str.replace('sushant lok phase 2', 'sector 57')
df['sector'] = df['sector'].str.replace('sushant lok phase 3', 'sector 57')
df['sector'] = df['sector'].str.replace('sushant lok', 'sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar phase 2', 'sector 4')
df['sector'] = df['sector'].str.replace('laxman vihar', 'sector 4')
df['sector'] = df['sector'].str.replace('uppals southend', 'sector 49')
df['sector'] = df['sector'].str.replace('malibu town', 'sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1', 'sector 104')
df['sector'] = df['sector'].str.replace('surat nagar phase 2', 'sector 104')
df['sector'] = df['sector'].str.replace('surat nagar', 'sector 104')
df['sector'] = df['sector'].str.replace('mianwali colony', 'sector 12')
df['sector'] = df['sector'].str.replace('jyoti park', 'sector 7')
df['sector'] = df['sector'].str.replace('jacobpura', 'sector 12')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension', 'sector 3')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2', 'sector 3')
df['sector'] = df['sector'].str.replace('ashok vihar phase i', 'sector 3')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3', 'sector 3')
df['sector'] = df['sector'].str.replace('ashok vihar', 'sector 3')
df['sector'] = df['sector'].str.replace('rajiv nagar', 'sector 12')
df['sector'] = df['sector'].str.replace('west rajiv nagar', 'sector 12')
df['sector'] = df['sector'].str.replace('subhash nagar', 'sector 78')
df['sector'] = df['sector'].str.replace('dayanand colony', 'sector 4')
df['sector'] = df['sector'].str.replace('new palam vihar phase 1', 'sector 110a')
df['sector'] = df['sector'].str.replace('new palam vihar phase 2', 'sector 110a')
df['sector'] = df['sector'].str.replace('new palam vihar', 'sector 110')
df['sector'] = df['sector'].str.replace('saraswati vihar', 'sector 28')
df['sector'] = df['sector'].str.replace('ansal plaza', 'sector 14')
df['sector'] = df['sector'].str.replace('chakkarpur', 'sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar', 'sector 7')
df['sector'] = df['sector'].str.replace('greenwood city', 'sector 45')
df['sector'] = df['sector'].str.replace('suncity', 'sector 54')
df['sector'] = df['sector'].str.replace('dharam colony', 'sector 12')
df['sector'] = df['sector'].str.replace('adarsh nagar', 'sector 12')
df['sector'] = df['sector'].str.replace('krishna colony', 'sector 7')
df['sector'] = df['sector'].str.replace('shivaji nagar', 'sector 4')
df['sector'] = df['sector'].str.replace('shivpuri', 'sector 7')
df['sector'] = df['sector'].str.replace('madanpuri', 'sector 7')
df['sector'] = df['sector'].str.replace('shakti nagar', 'sector 11')
df['sector'] = df['sector'].str.replace('gandhi nagar', 'sector 28')
df['sector'] = df['sector'].str.replace('patel nagar', 'sector 15')
df['sector'] = df['sector'].str.replace('mg road', 'sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden', 'sector 11')
df['sector'] = df['sector'].str.replace('mohan nagar', 'sector 5')
df['sector'] = df['sector'].str.replace('hira nagar', 'sector 4')
df['sector'] = df['sector'].str.replace('rajiv chowk', 'sector 28')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 7')
df['sector'] = df['sector'].str.replace('sispal vihar', 'sector 49')
df['sector'] = df['sector'].str.replace('manohar nagar', 'sector 5')
df['sector'] = df['sector'].str.replace('acharya puri', 'sector 4')
df['sector'] = df['sector'].str.replace('pratap nagar', 'sector 4')
df['sector'] = df['sector'].str.replace('daulatabad', 'sector 9')
df['sector'] = df['sector'].str.replace('iffco chowk', 'sector 28')
df['sector'] = df['sector'].str.replace('shanti nagar', 'sector 4')
df['sector'] = df['sector'].str.replace('lajpat nagar', 'sector 4')
df['sector'] = df['sector'].str.replace('mayfield garden', 'sector 51')
df['sector'] = df['sector'].str.replace('ambience island', 'sector 24')
df['sector'] = df['sector'].str.replace('rosewood', 'sector 49')
df['sector'] = df['sector'].str.replace('bhawani enclave', 'sector 105')
df['sector'] = df['sector'].str.replace('heritage city', 'sector 26')
df['sector'] = df['sector'].str.replace('south city 1', 'sector 41')
df['sector'] = df['sector'].str.replace('south city', 'sector 41')
df['sector'] = df['sector'].str.replace('khandsa', 'sector 17')
df['sector'] = df['sector'].str.replace('a block sushant lok phase 1', 'sector 43')
df['sector'] = df['sector'].str.replace('b block sushant lok phase 1', 'sector 43')
df['sector'] = df['sector'].str.replace('c block sushant lok phase 1', 'sector 43')

# --- IMT Manesar variants ---
df['sector'] = df['sector'].str.replace('sector 1 imt manesar', 'manesar')
df['sector'] = df['sector'].str.replace('sector 1a imt manesar', 'manesar')
df['sector'] = df['sector'].str.replace('imt manesar', 'manesar')
df['sector'] = df['sector'].str.replace('hsiidc plot sector 1 imt manesar', 'manesar')

# --- Sector X urban estate -> just sector X ---
df['sector'] = df['sector'].str.replace('sector 4 urban estate', 'sector 4')
df['sector'] = df['sector'].str.replace('urban estate, sector 5', 'sector 5')
df['sector'] = df['sector'].str.replace('urban estate sector 5', 'sector 5')

# Normal Once
df['sector'] = df['sector'].str.replace('prem nagar', 'sector 13')

In [85]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]

In [86]:
df = df[df['sector'].isin(a.index)]

In [87]:
df['sector'].value_counts()

sector
sohna road                   163
sector 102                   113
sector 85                    110
sector 92                    104
sector 69                     94
sector 90                     90
sector 81                     90
sector 65                     90
sector 109                    88
sector 79                     80
sector 104                    77
sector 83                     69
sector 4                      69
sector 37d                    68
sector 86                     67
sector 50                     65
sector 107                    60
sector 108                    59
sector 56                     57
sector 95                     57
sector 48                     56
sector 89                     56
sector 43                     55
sector 70a                    54
sector 70                     53
sector 37c                    53
sector 49                     52
sector 26                     51
sector 33 sohna road road     51
sector 28                     51
sector 84                     51
palam vihar                   50
sector 67                     48
sector 66                     46
sector 103                    45
sector 25                     43
sector 113                    43
sector 82                     42
sector 61                     42
sector 3                      42
sector 106                    38
sector 7                      35
manesar                       33
sector 99a                    32
sector 12                     31
sector 54                     31
sector 68                     30
sector 77                     29
sector 72                     29
sector 57                     29
sector 71                     27
sector 24                     26
sector 78                     24
sector 112                    24
sector 88a                    23
sector 33                     23
sector 111                    22
sector 67a                    22
sector 110                    21
sector 105                    21
sector 82a                    20
sector 14                     20
sector 22                     20
sector 47                     19
sector 74                     18
sector 63a                    18
sector 91                     17
sector 62                     17
sector 99                     16
sector 63                     15
sector 60                     15
gwal pahari                   14
sector 53                     14
sector 52                     14
sohna road road               14
sector 76                     14
sector 36a                    13
sector 46                     13
sector 11                     13
sector 93                     12
sector 38                     12
sector 41                     12
sector 39                     12
sector 31                     12
sector 5                      11
sector 9a                     11
sector 15                     10
sector 45                      9
sector 95a                     9
sector 55                      9
sector 51                      9
sector 89a                     8
mehrauli road                  8
sector 59                      8
c block sector 43              8
palam vihar extension          8
sector 40                      8
sector 10a                     8
dwarka expressway              8
new colony                     7
sector 36 sohna road           7
sector 110a                    7
sector 58                      7
sector 9                       7
sector 1                       6
sector 23a                     5
sector 30                      5
sector 17                      5
sector 80                      5
sector 2                       5
bhim nagar                     4
valley view estate             4
sector 13                      4
ravi nagar                     4
surya vihar                    4
sector 12a                     4
sector 36                      4
sector 3a                      4
sector 6                       4
vishnu garden                  4
new                            4
bhondsi                        4
baldev nagar                   4
garhi harsaru                  4
devilal colony                 4
sector 23                      3
sector 17a                     3
sector 73                      3
sector 8                       3
sector 88b                     3
b block sector 43              3
a block sector 43              3
sector 17b                     3
sector 27                      3
maruti kunj                    3
Name: count, dtype: int64

In [88]:
df['sector'] = df['sector'].str.replace('sector 33 sohna road road', 'sector 33')
df['sector'] = df['sector'].str.replace('palam vihar', 'sector 2')
df['sector'] = df['sector'].str.replace('gwal pahari', 'sector 2')
df['sector'] = df['sector'].str.replace('sohna road road', 'sohna road')
df['sector'] = df['sector'].str.replace('mehrauli road', 'sector 14')
df['sector'] = df['sector'].str.replace('c block sector 43', 'sector 43')
df['sector'] = df['sector'].str.replace('palam vihar extension', 'sector 23')
df['sector'] = df['sector'].str.replace('sector 36 sohna road', 'sector 36')

In [89]:
# --- Block normalization for already-numbered sectors ---
df['sector'] = df['sector'].str.replace('a block sector 43', 'sector 43')
df['sector'] = df['sector'].str.replace('b block sector 43', 'sector 43')

# --- Old Gurgaon colonies near sector 4/5/7/12 cluster ---
df['sector'] = df['sector'].str.replace('new colony', 'sector 7')
df['sector'] = df['sector'].str.replace('bhim nagar', 'sector 12')
df['sector'] = df['sector'].str.replace('ravi nagar', 'sector 4')
df['sector'] = df['sector'].str.replace('surya vihar', 'sector 4')
df['sector'] = df['sector'].str.replace('vishnu garden', 'sector 4')
df['sector'] = df['sector'].str.replace('baldev nagar', 'sector 7')
df['sector'] = df['sector'].str.replace('devilal colony', 'sector 9')

# --- Valley View Estate / Gwal Pahari area ---
df['sector'] = df['sector'].str.replace('valley view estate', 'sector 1')

# --- Maruti Kunj (near old Gurgaon / sector 18-19 industrial belt) ---
df['sector'] = df['sector'].str.replace('maruti kunj', 'sector 18')

df['sector'] = df['sector'].str.replace('sector 2 extension', 'sector 2')

In [90]:
df['sector'].value_counts()

sector
sohna road           177
sector 102           113
sector 85            110
sector 92            104
sector 69             94
sector 65             90
sector 81             90
sector 90             90
sector 109            88
sector 4              81
sector 79             80
sector 2              77
sector 104            77
sector 33             74
sector 43             69
sector 83             69
sector 37d            68
sector 86             67
sector 50             65
sector 107            60
sector 108            59
sector 56             57
sector 95             57
sector 48             56
sector 89             56
sector 70a            54
sector 37c            53
sector 70             53
sector 49             52
sector 26             51
sector 28             51
sector 84             51
sector 67             48
sector 66             46
sector 7              46
sector 103            45
sector 113            43
sector 25             43
sector 82             42
sector 61             42
sector 3              42
sector 106            38
sector 12             35
manesar               33
sector 99a            32
sector 54             31
sector 68             30
sector 77             29
sector 72             29
sector 57             29
sector 14             28
sector 71             27
sector 24             26
sector 78             24
sector 112            24
sector 88a            23
sector 67a            22
sector 111            22
sector 110            21
sector 105            21
sector 22             20
sector 82a            20
sector 47             19
sector 74             18
sector 63a            18
sector 62             17
sector 91             17
sector 99             16
sector 63             15
sector 60             15
sector 53             14
sector 76             14
sector 52             14
sector 36a            13
sector 11             13
sector 46             13
sector 93             12
sector 38             12
sector 39             12
sector 41             12
sector 31             12
sector 36             11
sector 5              11
sector 9a             11
sector 9              11
sector 1              10
sector 15             10
sector 55              9
sector 95a             9
sector 45              9
sector 51              9
sector 10a             8
sector 40              8
sector 59              8
sector 89a             8
dwarka expressway      8
sector 110a            7
sector 58              7
sector 17              5
sector 30              5
sector 23a             5
sector 80              5
sector 13              4
sector 12a             4
garhi harsaru          4
sector 6               4
sector 3a              4
new                    4
bhondsi                4
sector 27              3
sector 23              3
sector 73              3
sector 88b             3
sector 17b             3
sector 8               3
sector 17a             3
sector 18              3
Name: count, dtype: int64

In [91]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [92]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
185,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1920,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun-27,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2451,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2974,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN

In [93]:
df.loc[2974,'sector'] = 'sector 37'
df.loc[185,'sector'] = 'sector 92'
df.loc[2451,'sector'] = 'sector 90'
df.loc[1920,'sector'] = 'sector 76'

In [94]:
df.shape

(3856, 21)

In [95]:
df.duplicated().sum()

0

In [96]:
# Features to Drop

df.drop(columns=['property_name', 'address', 'description', 'rating'], inplace=True)

In [97]:
df.head()

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
0,flat,umang winter hills,sector 77,1.00,7500.0,1333.0,Carpet area: 1340 (124.49 sq.m.),2,2,2,not available,3.0,NaN,0 to 1 Year Old,"['Entertainland Mall', 'Delhi Jaipur Expresswa...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1,flat,emaar mgf emerald estate,sector 65,1.75,12544.0,1395.0,Super Built up area 1395(129.6 sq.m.)Carpet ar...,3,3,3,servant room,10.0,North-East,1 to 5 Year Old,"['Sector 53-54 Metro Station', 'Central Plaza ...","['1 Exhaust Fan', '3 Geyser', '7 Light', '1 Ch...","['Security / Fire Alarm', 'Intercom Facility',..."
2,house,suncity township,sector 54,2.00,30968.0,646.0,Plot area 60Built Up area: 60 sq.m.Carpet area...,9,9,3,servant room,11.0,North,1 to 5 Year Old,"['Sector 54 chowk metro station', 'Sector metr...","['1 Water Purifier', '9 Fan', '1 Fridge', '1 E...",['Internet/wi-fi connectivity']
3,house,independent,sector 108,1.70,5666.0,3000.0,Built Up area: 3000 (278.71 sq.m.)Carpet area:...,4,4,3+,not available,1.0,North-East,undefined,NaN,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN
4,flat,dlf the ultima,sector 81,2.30,10994.0,2092.0,Super Built up area 2092(194.35 sq.m.),3,4,3+,servant room,6.0,East,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...","['8 Fan', '1 Fridge', '1 Exhaust Fan', '7 Geys...","['Centrally Air Conditioned', 'Security / Fire..."

In [98]:
df.to_csv('Cleaned_properties_v1.csv', index=False)